WIP: Add JWT authentication capabilities
VPH-Share/atmosphere-vph pull request #18
Opened 2016-12-13 13:53 UTC by nowakowski

2016-12-14 08:11 UTC, mkasztelnik requested changes
Small fixes are required.

2016-12-14 08:11 UTC, mkasztelnik commented on lib/devise/strategies/jwt_authenticatable.rb
> +        super || token # Why super? Should always return false
I believe token should be enough here

2016-12-14 08:11 UTC, mkasztelnik commented on lib/devise/strategies/jwt_authenticatable.rb
> +        return fail(:invalid_token) if @token.blank? # Is a more sophisticated check required here?
Don't use `@token` since getter method for this lazy loading value is available (`token`)

2016-12-14 08:11 UTC, mkasztelnik commented on config/application.yml
> +    key: <%= Rails.root.join('config', 'jwt', 'dev.pem') %>
This value is used also in production env which is not what we want. Dedicated entry with jwt key should be defined for prod env.

2016-12-14 08:11 UTC, mkasztelnik commented on app/models/concerns/atmosphere/user_ext.rb
> +
Please compact a little bit this method by removing extra empty lines. What is more please re-think if all debug messages are needed in this method.

2016-12-14 08:11 UTC, mkasztelnik commented on app/models/concerns/atmosphere/user_ext.rb
> +    attr_accessor :mi_ticket, :jwt_token, :project
Where this accessor is used and when/where is it set?

2016-12-18 14:45 UTC, nowakowski commented on config/application.yml
> +    key: <%= Rails.root.join('config', 'jwt', 'dev.pem') %>
Okay, but - this being a private key - we do not want to commit `prod.pem` to Github. Should I modify `config/application.yml` to seek this file in `config/jwt` regardless?

2016-12-18 14:51 UTC, nowakowski commented on lib/devise/strategies/jwt_authenticatable.rb
> +        super || token # Why super? Should always return false
Changed.

2016-12-18 14:51 UTC, nowakowski commented on lib/devise/strategies/jwt_authenticatable.rb
> +        return fail(:invalid_token) if @token.blank? # Is a more sophisticated check required here?
Changed.

2016-12-18 14:51 UTC, nowakowski commented on app/models/concerns/atmosphere/user_ext.rb
> +    attr_accessor :mi_ticket, :jwt_token, :project
Unnecessary. Fixed.

2016-12-18 14:51 UTC, nowakowski commented on app/models/concerns/atmosphere/user_ext.rb
> +
Yup.

2016-12-18 15:22 UTC, mkasztelnik commented on config/application.yml
> +    key: <%= Rails.root.join('config', 'jwt', 'dev.pem') %>
Configuration for production should be added. Private key should no t be committed. We should copy it into the place where atmo will be running. Take a look at https://gitlab.com/eurvalve/vapor/blob/master/config/application.yml#L21-25 and vapor installation for examples.

2016-12-18 15:24 UTC, mkasztelnik requested changes

2016-12-18 15:24 UTC, mkasztelnik commented on lib/devise/strategies/jwt_authenticatable.rb
> +        return fail(:invalid_token) if token.blank? # Is a more sophisticated check required here?
If more sophisticated check if needed there than please add it, remove comment otherwise

2016-12-18 16:44 UTC, mkasztelnik commented on config/application.yml
> +    key: <%= Rails.root.join('config', 'jwt', 'dev.pem') %>
What is more to check if token is signed by concrete key you need only public key. Please consult it with @dharezlak - he already done something similar for valve file store.

2016-12-19 10:19 UTC, mkasztelnik commented
There also would be nice to have set of public keys for validating valve token to supports both valve-dev and valde-prod portals. @nowakowski is it doable?

2016-12-19 14:14 UTC, nowakowski commented
@mkasztelnik Done. Multiple EC keys can now be registered for each environment. The system will iterate through the available keys when authorizing requests until success is achieved or until we run out of keys. I've also added specs to test this behavior. Finally, I included the Vapor public key in default config.

2016-12-19 14:55 UTC, nowakowski commented on config/application.yml
> +    key: <%= Rails.root.join('config', 'jwt', 'dev.pem') %>
Done as requested. Seems to work (at least on my laptop). I've also written specs to test this.

2016-12-20 15:28 UTC, mkasztelnik approved these changes
Ok I'm fine with this code :+1:

2016-12-27 13:56 UTC, merged